services:
  lbx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/lbx/config.yml
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - mynet

  server1: 
    image: subrotokumar/httpserver
    ports:
      - "3001:3000"
    environment:
      - SERVICE=server1
    networks:
      - mynet
    
  server2: 
    image: subrotokumar/httpserver
    ports:
      - "3002:3000"
    environment:
      - SERVICE=server2
    networks:
      - mynet

  server3: 
    image: subrotokumar/httpserver
    ports:
      - "3003:3000"
    environment:
      - SERVICE=server3
    networks:
      - mynet

networks:
  mynet:
    driver: bridge